# Generated by Django 5.1.3 on 2024-11-12 00:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_evaluacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='descripcion',
            field=models.TextField(default='Descripción pendiente'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 0, 11, 15, 152551, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='titulo',
            field=models.CharField(default='Título Predeterminado', max_length=200),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
