# Generated by Django 5.1.3 on 2024-11-13 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0003_evaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='estado',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 13, 36, 12, 980230, tzinfo=datetime.timezone.utc)),
        ),
    ]
