# Generated by Django 5.1.3 on 2024-11-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0004_remove_evaluacion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_vencimiento',
        ),
    ]
