# Generated by Django 5.1.3 on 2024-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0005_remove_evaluacion_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='comentarios',
            field=models.TextField(default='Comentario pendiente'),
        ),
    ]
