# Generated by Django 5.1.3 on 2024-11-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0006_remove_evaluacion_descripcion_evaluacion_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='fecha_creacion',
            new_name='fecha_evaluacion',
        ),
    ]
