# Generated by Django 5.1.3 on 2024-11-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0007_rename_fecha_creacion_evaluacion_fecha_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reveloper.tareapordesarrollar'),
        ),
    ]
