# Generated by Django 5.1.3 on 2024-11-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0008_evaluacion_tarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TareaDesarrollada',
        ),
    ]
