# Generated by Django 5.1.3 on 2024-11-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0009_delete_tareadesarrollada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='tareapordesarrollar',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.CreateModel(
            name='TareasCompletadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_original_id', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Completada',
                'verbose_name_plural': 'Tareas Completadas',
            },
        ),
    ]
