# Generated by Django 5.1.3 on 2024-11-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0010_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tareas_completadas',
            field=models.IntegerField(default=0),
        ),
    ]
