# Generated by Django 5.1.3 on 2024-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0011_usuario_tareas_completadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareapordesarrollar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En Progreso'), ('completada', 'Completada'), ('en revision', 'En Revisión')], max_length=20),
        ),
    ]
