# Generated by Django 5.1.3 on 2024-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0012_alter_tareapordesarrollar_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_entrega', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('complejidad_tarea', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('cumplimiento_requerimientos', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('calidad_codigo', models.DecimalField(decimal_places=1, default=25.0, max_digits=4)),
                ('nota_maxima', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Criterio Evaluación',
                'verbose_name_plural': 'Criterios Evaluaciones',
            },
        ),
    ]
