# Generated by Django 5.1.3 on 2024-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0012_alter_tareapordesarrollar_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_entrega', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('complejidad_tarea', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('numero_revisiones', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
            ],
        ),
    ]
