# Generated by Django 5.1.3 on 2026-07-30 15:34

import django.db.models.deletion
from django.db import migrations, models


def detach_older_duplicate_evaluations(apps, schema_editor):
    Evaluacion = apps.get_model('Reveloper', 'Evaluacion')

    duplicate_task_ids = (
        Evaluacion.objects
        .exclude(tarea_id__isnull=True)
        .values('tarea_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('tarea_id', flat=True)
    )

    for tarea_id in duplicate_task_ids:
        evaluation_ids = list(
            Evaluacion.objects
            .filter(tarea_id=tarea_id)
            .order_by('-fecha_evaluacion', '-id')
            .values_list('id', flat=True)
        )

        older_evaluation_ids = evaluation_ids[1:]

        Evaluacion.objects.filter(
            id__in=older_evaluation_ids
        ).update(tarea_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('Reveloper', '0014_alter_evaluacionconfig_defaults'),
    ]

    operations = [
        migrations.RunPython(
            detach_older_duplicate_evaluations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tarea',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='Reveloper.tareapordesarrollar',
            ),
        ),
    ]